letscook/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/search_results' => 'recipes#search_results'
  get '/search_results/:recipe_id' => 'recipes#search_result'

  resources :users, except: [:index] do
    resources :recipes
    get '/grocery_list' => 'grocery_lists#show'
    patch '/grocery_list' => 'grocery_lists#update'
  end

  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

end

letscook/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user

  serialize :ingredients, Array
  serialize :instructions, Array

  validates :title,
    presence: true


end

letscook/app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  has_many :grocery_lists
  before_create :create_logged_in_user
  before_save :normalize_fields

  validates :name,
    presence: true,
    length: { maximum: 50 }

  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password

  def User.new_logged_in_user
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_logged_in_user
    self.logged_in_user = User.hash(User.new_logged_in_user)
  end

  def normalize_fields
    self.email.downcase!
  end


end

letscook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

letscook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action(:find_user, except: [:search_results])
  before_action(:new_recipe, only: [:search_result, :new, :create])
  before_action(:find_recipe, only: [:show, :edit, :update, :destroy])

  def search_results
    @search_terms = params[:q].gsub(" ", "+")
    response_hash = HTTParty.get("http://api.bigoven.com/recipes?any_kw=#{@search_terms}&pg=1&rpp=20&api_key=#{ENV["MY_API_KEY"]}")
    @search_results = response_hash["RecipeSearchResult"]["Results"]["RecipeInfo"]
  end

  def search_result
    get_json

  end

  def new
  end

  def create
    @recipe[:title] = params["recipe"]["title"]
    @recipe[:imageURL] = params["recipe"]["imageURL"]
    @recipe[:description] = params["recipe"]["description"]
    @recipe[:cuisine] = params["recipe"]["cuisine"]
    @recipe[:ingredients] = params["recipe"]["ingredients"].split("$")
    @recipe[:instructions] = params["recipe"]["instructions"].split("$")
    @recipe[:yield] = params["recipe"]["yield"]
    @recipe[:time] = params["recipe"]["time"]
    @recipe[:user_id] = params[:user_id]
    @recipe.save
    redirect_to user_recipes_path(@user)
  end

  def index
    @recipes = Recipe.where(user_id: @user.id)
  end

  def show
  end

  def edit
  end

  def update
    @recipe[:title] = params[:recipe][:title]
    @recipe[:imageURL] = params[:recipe][:imageURL]
    @recipe[:description] = params[:recipe][:description]
    @recipe[:cuisine] = params[:recipe][:cuisine]
    @recipe[:ingredients] = params[:recipe][:ingredients].split(', ')
    @recipe[:instructions] = params[:recipe][:instructions].split('. ')
    @recipe[:yield] = params[:recipe][:yield]
    @recipe[:time] = params[:recipe][:time]
    @recipe[:user_id] = params[:user_id]
    @recipe.save
    redirect_to user_recipes_path(@user)
  end

  def destroy
    @recipe.destroy
    redirect_to user_recipes_path
  end

  private

  def get_json
    @recipe_id = params[:recipe_id]
    response = HTTParty.get("http://api.bigoven.com/recipe/#{@recipe_id}?api_key=#{ENV["MY_API_KEY"]}")
    @recipe_imageURL = response["Recipe"]["ImageURL"]
    @recipe_title = response["Recipe"]["Title"]
    @recipe_description = response["Recipe"]["Description"]
    @recipe_cuisine = response["Recipe"]["Cuisine"]
    @recipe_yield = response["Recipe"]["YieldNumber"].to_s + " " + response["Recipe"]["YieldUnit"].to_s
    @recipe_time = response["Recipe"]["TotalMinutes"]
    @recipe_rating = response["Recipe"]["StarRating"].to_f.round(2)
    @recipe_ingredient_array = response["Recipe"]["Ingredients"]["Ingredient"].map do |ingredient_hash|
      "#{ingredient_hash["Quantity"].to_f.round(2) } #{ingredient_hash["Unit"]} #{ingredient_hash["Name"]}"
    end
    @recipe_instructions = response["Recipe"]["Instructions"].split(". ")
  end

  def recipe_params
    params.require(:recipe).permit(:title, :imageURL, :description, :cuisine, )
  end

  def find_user
    @user = current_user
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def new_recipe
    @recipe = Recipe.new
  end

end

letscook/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # Find the user by email:
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash[:error] = 'Invalid email/password'
      redirect_to signin_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

letscook/app/controllers/users_controller.rb
class UsersController <  ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render  :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
      )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

letscook/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

letscook/app/helpers/application_helper.rb
module ApplicationHelper
end

letscook/app/helpers/sessions_helper.rb
module SessionsHelper

  # Current User methods:

  def current_user
    logged_in_user = User.hash(cookies[:logged_in_user])
    @current_user ||= User.find_by(logged_in_user: logged_in_user)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  # Signin Status methods:

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    logged_in_user = User.new_logged_in_user
    cookies.permanent[:logged_in_user] = logged_in_user
    user.update_attribute(:logged_in_user, User.hash(logged_in_user))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:logged_in_user, User.hash(User.new_logged_in_user))
    cookies.delete(:logged_in_user)
    self.current_user = nil
  end

  # Location Management methods:

  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Security Checkpoint method:

  def require_signin
    unless signed_in?
      store_location
      flash[:error] = 'Please sign in.'
      redirect_to signin_url
    end
  end
end

letscook/app/helpers/welcome_helper.rb
module WelcomeHelper
end

letscook/app/views/common/_signout.html.erb
<% if signed_in? %>

  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    <span class="welcomeuser">Welcome, <%= link_to current_user.name, current_user %>!</span>
    <span class="signout"><%= f.submit "Sign out", id: 'signout' %></span>
  <% end %>

  <span class="searchbanner"><%= link_to "Search", root_path %></span>
<br>
  <span class="mycookbooklink"><%= link_to "My Cookbook", user_recipes_path(current_user) %></span>
  <br>
  <span class="mygrocerylistlink"><%= link_to "My Grocery List", user_grocery_list_path(current_user) %></span>

<% else %>
  <span class="loggedoutbanner">Sign up or log in to save recipes to your cookbook!</span>
<br>
  <span class="signinsignup"><%= link_to "Sign In", signin_path %> | <%= link_to "Sign up", signup_path %></span>
<br>
  <span class="searchbanner"><%= link_to "Search", root_path %></span>

<% end %>

letscook/app/views/welcome/index.html.erb
<div class="homepage">
  <div class = "navbar navbar-inverse navbar-static-top">
    <div class = "container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class = "icon-bar"></span>
          <span class = "icon-bar"></span>
          <span class = "icon-bar"></span>
        </button>
        <a href="#" class = "navbar-brand">Let's Cook Something!</a>
      </div>
      <center>
        <div id="navbar" class="navbar-collapse collapse">
          <% if !signed_in? %>
            <%= form_for :session, :html => {class: 'navbar-form navbar-right'}, url: sessions_path do |f| %>
              <div class="form-group">
                <%= f.text_field :email, :class => 'form-control', :placeholder => 'Email' %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, :class => 'form-control', :placeholder => 'Password' %>
              </div>
              <%= f.submit 'Sign in', id: 'signin', :class => 'btn btn-primary' %>
            <% end %>
          <% else %>
            <div class="navbar-welcome navbar-right">Welcome <%= current_user.name %>!</div>
          <% end %>
        </div>
      </center>
    </div>
  </div>
  <div class="main">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="main__wrapper">
            <h1 class="main__wrapper__header">Let's Cook Something!</h1>
            <%= form_tag("/search_results", method: "get", :class => "main__wrapper__form") do %>
              <div class="input-group">
                <%= text_field_tag(:q, nil, :placeholder => "What do you want to eat today?", :class => "form-control input-lg") %>
                <span class="input-group-btn">
                  <%= submit_tag("Search", :class => "btn btn-primary btn-lg") %>
                </span>
              </div>
            <% end %>
            <% if signed_in? %>
              <div class="main__wrapper__create-your-own">
                <%= link_to "Create your own recipe", new_user_recipe_path(current_user), :class => "" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>